### ISSUE TITLE
Webview is not rendering

### ISSUE THREAD

**Issue by facusantillo** [webdriverio/native-demo-app#101]
**Environment (please complete the following information):**
 - Node.js version: [12.19]
 - NPM version: [6.14.0]
 - Platform: [Android]
 - Platform version: [14.0]
 - Emulator/Simulator/Real Device: [Emulator]

**Describe the bug**
The webview is not being rendered

**To Reproduce**
Open app
Tap webview

**Expected behavior**
Should render the webview

**Comment by wswebcreation** [comment]
Thanks for filing an issue @facusantillo 

This is a know issue, the app needs to be updated with the latest dependencies. I'll see when I have some time for this so I can release a new version

**Comment by wswebcreation** [comment]
Hi @facusantillo 

I'm working on a PR to upgrade all dependencies, see https://github.com/webdriverio/native-demo-app/pull/102
