### ISSUE TITLE
Add IPA file to downloads in assets

### ISSUE THREAD

**Issue by facusantillo** [webdriverio/native-demo-app#110]
**Business case**
Some services like browserstack uses .IPA in real devices. We use the app as part of the unit tests on our framework around appium. Last release didn't included the IPA files. 

**Describe the solution you'd like**
IPA files should be uploaded with the assets

**Comment by wswebcreation** [comment]
Hi @facusantillo 

Tanks for filling an issue. I didn't add the `.ipa`-file because it needs to be signed with a paid developer certificate of Apple. Currently we don't have one. Feel free to build the app with your own Apple Developer certificate and upload it to us.
