### ISSUE TITLE
iOS 16.4 Fails to get webview context

### ISSUE THREAD

**Issue by itkhanz** [webdriverio/native-demo-app#128]
**Environment (please complete the following information):**
JDK 11.0.2
Appium 2.0.0-rc.3
appium-java-client 8.5.1
appium xcuitest driver 4.32.5
selenium-java 4.9.1
Node v18.16.0
NPM 9.6.7
macOS Ventura 13.4
XCode 14.3
iPhone 14 (iOS 16.4 simulator)

**Describe the bug**
Launching the Demo app on iOS 16.4 simulator and Clicking on WebView.
Appium Inspector fails to switch to WebView and does not load the webview context.
Also in the commands tab, if you execute the Get Context List command, then the webview is not detected.

I have also tried to get the webview context with Appium Java client code, but it also does not find the webview context. 
```
IOSDriver driver = (IOSDriver)DriverManager.getDriver();

System.out.println("Current context " + driver.getContext());
System.out.println("Current available contexts " + driver.getContextHandles());

driver.findElement(AppiumBy.accessibilityId("Webview")).click();
Thread.sleep(10000);
System.out.println("handles " + driver.getContextHandles());



Set<String> handles = driver.getContextHandles();
for (String contextName : handles) {
    System.out.println(contextName); //prints out something like NATIVE_APP \n WEBVIEW_1
}
```

It only prints the **NATIVE_APP** as detected context and available contexts. 
attached you will also find the server logs.
[appium-server-logs.txt](https://github.com/webdriverio/native-demo-app/files/11815958/appium-server-logs.txt)

**Screenshots**
If you run the above code on iOS 16.2 simulator then you get the webview context also **WEBVIEW_25733.3**
With iOS 16.2, Appium Inspector can successfully switch context to WebView.
![Screenshot 2023-06-21 at 10 50 56](https://github.com/webdriverio/native-demo-app/assets/62521743/a93b8d04-9905-485a-9a16-0952dfb0b869)

But with iOS 16.4 Appium Inspector is unable to switch to WebView.

**Additional context**
There is a thread ongoing on Appium discussion forum that suggests new properties to be set by developers in code to make the webview context switching possible with iOS 16.4 and higher.

https://discuss.appium.io/t/webview-context-switching-not-working-on-ios-16-2/39354/11

https://github.com/appium/appium-xcuitest-driver/blob/master/docs/device-preparation.md#if-iosipados-version-is-164-or-above

If the bug is due to missing configuration in application code, please release the new version of demo app with patch for iOS 16.4 or higher for webview context detection and switcing.

**Comment by wswebcreation** [comment]
OS level rights have changed for iOS 16 and Android 13+. Please try the latest version
