### ISSUE TITLE
Can't build iOS app with current versions and latest Xcode 10.3

### ISSUE THREAD

**Issue by viktorgogulenko** [webdriverio/native-demo-app#5]
**Environment (please complete the following information):**
 - Node.js version: 8.9.3
 - NPM version: 6.10.3
 - Platform: iOS
 - Platform version: 12.4.1
 - Emulator/Simulator/Real Device: Simulator, Real Device
 - Xcode version: 10.3

**Describe the bug**
I was trying to build an iOS application and to run it at least on Simulator, but it failed. I cloned your project, made 'npm install' and then 'npm run ios', but it failed with error:

> $ npm run ios

> native-demo-app@0.2.1 ios /Users/myuser/Documents/Projects/wdio-demo-native-demo-app
> react-native run-ios

> Scanning folders for symlinks in /Users/myuser/Documents/Projects/wdio-demo-native-demo-app/node_modules (10ms)
> Found Xcode project wdioDemoApp.xcodeproj
> 
> Could not find iPhone 6 simulator
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! native-demo-app@0.2.1 ios: `react-native run-ios`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the native-demo-app@0.2.1 ios script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Then I've tried to make 'npm fix audit' and execute 'npm run ios' again. It failed with error:

> $ npm run ios

> native-demo-app@0.2.1 ios /Users/myuser/Documents/Projects/wdio-demo-native-demo-app
> react-native run-ios

> warn The following packages use deprecated "rnpm" config that will stop working from next release:
>   - react-native-vector-icons: https://github.com/oblador/react-native-vector-icons
> Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
> error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
>   - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
> This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
> Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
> info Found Xcode project "wdioDemoApp.xcodeproj"
> info Launching iPhone X (iOS 12.4)
> info Building (using "xcodebuild -project wdioDemoApp.xcodeproj -configuration Debug -scheme wdioDemoApp -destination id=ADB20338-FC68-48DD-9A5F-231B32665660 -derivedDataPath build/wdioDemoApp")
> .............
> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening wdioDemoApp.xcodeproj. Run CLI with --verbose flag for more details.
> User defaults from command line:
>     IDEDerivedDataPathOverride = /Users/vgogulen/Documents/Projects/wdio-demo-native-demo-app/ios/build/wdioDemoApp
> 
> note: Using new build system
> note: Planning build
> note: Constructing build description
> Build system information
> error: Unable to resolve build file: XCBCore.BuildFile (missingTargetProductReference("d7c9a29262ff4df7424daeb0427a745529fe2a87b7c65fea7a8f025b04a3b7ff")) (in target 'wdioDemoApp')
> 
> Build system information
> warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'RNVectorIcons')
> 
> 
> 2019-09-02 09:59:10.272 xcodebuild[9771:1190678]  DTDeviceKit: deviceType from bc74ac5dc57b3d479597338e686d58dccc4d9f43 was NULL
> 2019-09-02 09:59:10.304 xcodebuild[9771:1190645]  DTDeviceKit: deviceType from 00008020-0004248A3645002E was NULL
> 2019-09-02 09:59:10.343 xcodebuild[9771:1190646]  DTDeviceKit: deviceType from bc74ac5dc57b3d479597338e686d58dccc4d9f43 was NULL
> 2019-09-02 09:59:10.366 xcodebuild[9771:1190679]  DTDeviceKit: deviceType from 00008020-0004248A3645002E was NULL
> ** BUILD FAILED **
> 
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! native-demo-app@0.2.1 ios: `react-native run-ios`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the native-demo-app@0.2.1 ios script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Expected behavior**
Could you please update iOS part, so it could be built and launched on latest Xcode (10.3) and ran it on Simulator? Thanks in advance!

**Comment by wswebcreation** [comment]
Hi @viktorgogulenko 

This is an issue with React Native, if you would got to this file `./node_modules/react-native/local-cli/runIOS/findMatchingSimulator.js` and change the `if`-statement to 

`if (!version.includes('iOS') && !version.includes('tvOS')) {` it should work.

You can also download the latest versions from the releases tab

I got refactoring this app to the latest version of React Native on my to-do list

**Comment by viktorgogulenko** [comment]
@wswebcreation thanks for the hint! FYI: I was able to build an application, but it crashed as soon as it was started on Simulator with such issue:
<img width="510" alt="Screenshot 2019-09-02 at 14 46 38" src="https://user-images.githubusercontent.com/12098350/64115809-db50c880-cd90-11e9-8349-78ccac20a868.png">

**Comment by wswebcreation** [comment]
As said, I need to dive into it, but currently don't have the time for it.

**Comment by wswebcreation** [comment]
@viktorgogulenko 

I've opened a PR for upgrading to the latest version of RN, see https://github.com/webdriverio/native-demo-app/pull/6. This would allow you to run it locally again, please see the readme

**Comment by wswebcreation** [comment]
@viktorgogulenko 

It's almost done, we only need to wait for Appium `1.15.0` and I'll merge the PR into master and release a new version

**Comment by wswebcreation** [comment]
@viktorgogulenko 

I've merged the latest RN 0.60 release into master. It now supports iOS 13. I'm going to close it for now

**Comment by viktorgogulenko** [comment]
@wswebcreation thanks a lot! Just tried to build - successfully built from command-line using _yarn_ and from Xcode 11 as well!
